version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - "5434:5432"

volumes:
  node_modules:
